version: '3.8'
services:
  veritabanimiz:
    image: postgres:15-alpine
    container_name: german-word-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: germanword_db
    ports:
      - "5432:5432"